# Default values for valkey-backup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# This parameter is required.
# Name of the instance to connect and backup
#valkey_instance_name: valkey-sentinel-ssl

#namespace: default

#Docker image to be used 
image: 
  repository: quay.io/david_andino/valkey-backup
  tag: v0.0.2
  #debug: false

cronjob:
  # if enabled you can customize the schedule time, if disabled then it will run just a job (used for testing purposes)
  enabled: false
  # ┌───────────── minute (0 - 59)
  # │ ┌───────────── hour (0 - 23)
  # │ │ ┌───────────── day of the month (1 - 31)
  # │ │ │ ┌───────────── month (1 - 12)
  # │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday)
  # │ │ │ │ │                                   OR sun, mon, tue, wed, thu, fri, sat
  # │ │ │ │ │
  # │ │ │ │ │
  # * * * * *
  # If not assigned will be added to every midnight
  #schedule: "0 0 * * *"

valkey:
  use_tls: "false"
  # The secret certificate has to contain the following data: ca.crt, tls.crt and tls.key
  #certificates_secret: secret_name_with_certificates

# Password of the restic which is required,
# if not provided will be generated
#restic_password:

# Required S3 connection information
#
#s3:
#  access_key:
#  secret_key:
#  bucket_name:
#  region:
#  host:
#  port:
#  use_ssl: # true or false
